service: users-private

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

appSync:
  name: private-api

  logging:
    level: ALL

  schema:
    - ../assets/schemas/*.graphql
    - schema.graphql

  authentication:
    type: API_KEY

  apiKeys:
    - name: Private
      expiresAfter: 1y

  dataSources:
    # common dataSources
    - ${file(../assets/templates/dataSources.yml)}

  resolvers:
    # common resolvers
    - ${file(../assets/templates/usersResolvers.yml)}

    # private only resolvers
    - Mutation.createUser: users
      Mutation.updateUser: users
